[package]
name = "videatitles"
version = "2022.5.16"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking"]}
regex = "1.5"
clap = "3.1"
crossterm = "0.23"
